import type { Metadata } from "next";
import "./globals.css";
import {AuthContext} from "@/helpers/AuthContext";
import {ThemeProvider} from "next-themes";
import {NavBar} from "@/components/ui/NavBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
        <body
            className="min-h-screen"
        >
        <AuthContext>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                <NavBar/>
                {children}
            </ThemeProvider>
        </AuthContext>
        </body>
        </html>
    );
}
